cask_args appdir: '/Applications'

tap 'caskroom/versions'
tap 'caskroom/cask'
tap 'caskroom/fonts'

brew 'git'
brew 'nvm'
brew 'pipenv'
brew 'pyenv'
brew 'wget'
brew 'zsh'

cask 'alfred'
cask 'caffeine'
cask 'docker'
cask 'flux'
cask 'google-chrome'
cask 'iterm2'
cask 'postman'
cask 'slack'
cask 'sourcetree'
cask 'the-unarchiver'
cask 'visual-studio-code'
cask 'appcleaner'
cask 'figma'
cask 'firefox'
cask 'slack'
